# Generated by Django 5.2.6 on 2025-09-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='news_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('clothes', 'Clothes'), ('jersey', 'Jersey'), ('accessory', 'Accessory'), ('shoes', 'Shoes'), ('merchandise', 'Merchandise')], default='clothes', max_length=20),
        ),
    ]
