# Generated by Django 5.2.6 on 2025-09-28 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_news_views_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='news_views',
            new_name='product_views',
        ),
    ]
